#ifndef CONFIG_H
#define CONFIG_H

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
#define FOV 70.0f
#define NEAR_PLANE 0.1f
#define FAR_PLANE 500.0f

#define CHUNK_SIZE 16
#define CHUNK_HEIGHT 256
#define RENDER_DISTANCE 8
#define SEA_LEVEL 64

#define TERRAIN_OCTAVES 6
#define TERRAIN_PERSISTENCE 0.5f
#define TERRAIN_LACUNARITY 2.0f
#define TERRAIN_SCALE 0.02f
#define TERRAIN_HEIGHT_MULTIPLIER 40
#define TERRAIN_BASE 50

#define PLAYER_HEIGHT 1.8f
#define PLAYER_EYE_HEIGHT 1.62f
#define PLAYER_RADIUS 0.3f
#define PLAYER_SPEED 4.3f
#define PLAYER_SPRINT_MULTIPLIER 1.3f
#define PLAYER_JUMP_SPEED 8.0f
#define GRAVITY 32.0f
#define MOUSE_SENSITIVITY 0.15f

#define TERMINAL_VELOCITY 50.0f
#define FRICTION 0.9f

#define REACH_DISTANCE 5.0f
#define BLOCK_PLACE_COOLDOWN 0.25f

#define MAX_CHUNKS_PER_FRAME 4

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

#endif